// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hypervane.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessEvent_Kind int32

const (
	ProcessEvent_STARTED ProcessEvent_Kind = 0
	ProcessEvent_STOPPED ProcessEvent_Kind = 1
	ProcessEvent_CRASHED ProcessEvent_Kind = 2
	ProcessEvent_METRICS ProcessEvent_Kind = 3
)

// Enum value maps for ProcessEvent_Kind.
var (
	ProcessEvent_Kind_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
		2: "CRASHED",
		3: "METRICS",
	}
	ProcessEvent_Kind_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
		"CRASHED": 2,
		"METRICS": 3,
	}
)

func (x ProcessEvent_Kind) Enum() *ProcessEvent_Kind {
	p := new(ProcessEvent_Kind)
	*p = x
	return p
}

func (x ProcessEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_hypervane_proto_enumTypes[0].Descriptor()
}

func (ProcessEvent_Kind) Type() protoreflect.EnumType {
	return &file_hypervane_proto_enumTypes[0]
}

func (x ProcessEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessEvent_Kind.Descriptor instead.
func (ProcessEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{4, 0}
}

type PreviewReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RomId         string                 `protobuf:"bytes,1,opt,name=rom_id,json=romId,proto3" json:"rom_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // absolute path to encoded .mp4/.webm loop
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewReady) Reset() {
	*x = PreviewReady{}
	mi := &file_hypervane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewReady) ProtoMessage() {}

func (x *PreviewReady) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewReady.ProtoReflect.Descriptor instead.
func (*PreviewReady) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewReady) GetRomId() string {
	if x != nil {
		return x.RomId
	}
	return ""
}

func (x *PreviewReady) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ScrapeProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RomId         string                 `protobuf:"bytes,1,opt,name=rom_id,json=romId,proto3" json:"rom_id,omitempty"`
	Percent       float32                `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"` // "fetch" | "encode" | "done" | "error"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeProgress) Reset() {
	*x = ScrapeProgress{}
	mi := &file_hypervane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeProgress) ProtoMessage() {}

func (x *ScrapeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeProgress.ProtoReflect.Descriptor instead.
func (*ScrapeProgress) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeProgress) GetRomId() string {
	if x != nil {
		return x.RomId
	}
	return ""
}

func (x *ScrapeProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *ScrapeProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ScrapeProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RomId         string                 `protobuf:"bytes,1,opt,name=rom_id,json=romId,proto3" json:"rom_id,omitempty"`
	RomPath       string                 `protobuf:"bytes,2,opt,name=rom_path,json=romPath,proto3" json:"rom_path,omitempty"`
	EmulatorId    string                 `protobuf:"bytes,3,opt,name=emulator_id,json=emulatorId,proto3" json:"emulator_id,omitempty"`                                                       // "duckstation" | "dolphin" | "retroarch" | ...
	Overrides     map[string]string      `protobuf:"bytes,4,rep,name=overrides,proto3" json:"overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // per-launch config overrides
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_hypervane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{2}
}

func (x *LaunchRequest) GetRomId() string {
	if x != nil {
		return x.RomId
	}
	return ""
}

func (x *LaunchRequest) GetRomPath() string {
	if x != nil {
		return x.RomPath
	}
	return ""
}

func (x *LaunchRequest) GetEmulatorId() string {
	if x != nil {
		return x.EmulatorId
	}
	return ""
}

func (x *LaunchRequest) GetOverrides() map[string]string {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_hypervane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{3}
}

func (x *KillRequest) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ProcessEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ProcessEvent_Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=hypervane.ProcessEvent_Kind" json:"kind,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	RomId         string                 `protobuf:"bytes,3,opt,name=rom_id,json=romId,proto3" json:"rom_id,omitempty"`
	RuntimeMs     uint64                 `protobuf:"varint,4,opt,name=runtime_ms,json=runtimeMs,proto3" json:"runtime_ms,omitempty"`
	CrashInfo     string                 `protobuf:"bytes,5,opt,name=crash_info,json=crashInfo,proto3" json:"crash_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_hypervane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessEvent) GetKind() ProcessEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return ProcessEvent_STARTED
}

func (x *ProcessEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessEvent) GetRomId() string {
	if x != nil {
		return x.RomId
	}
	return ""
}

func (x *ProcessEvent) GetRuntimeMs() uint64 {
	if x != nil {
		return x.RuntimeMs
	}
	return 0
}

func (x *ProcessEvent) GetCrashInfo() string {
	if x != nil {
		return x.CrashInfo
	}
	return ""
}

type RomEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      uint64                 `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Crc32         string                 `protobuf:"bytes,7,opt,name=crc32,proto3" json:"crc32,omitempty"`
	Sha1          string                 `protobuf:"bytes,8,opt,name=sha1,proto3" json:"sha1,omitempty"`
	Verified      bool                   `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"` // matched against No-Intro / Redump
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomEntry) Reset() {
	*x = RomEntry{}
	mi := &file_hypervane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomEntry) ProtoMessage() {}

func (x *RomEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomEntry.ProtoReflect.Descriptor instead.
func (*RomEntry) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{5}
}

func (x *RomEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RomEntry) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RomEntry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RomEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *RomEntry) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *RomEntry) GetCrc32() string {
	if x != nil {
		return x.Crc32
	}
	return ""
}

func (x *RomEntry) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *RomEntry) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // optional filter
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_hypervane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RomEntry            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalHits     uint32                 `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_hypervane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*RomEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalHits() uint32 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_PreviewReady
	//	*Envelope_ScrapeProgress
	//	*Envelope_LaunchRequest
	//	*Envelope_KillRequest
	//	*Envelope_ProcessEvent
	//	*Envelope_SearchRequest
	//	*Envelope_SearchResponse
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_hypervane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_hypervane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_hypervane_proto_rawDescGZIP(), []int{8}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPreviewReady() *PreviewReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PreviewReady); ok {
			return x.PreviewReady
		}
	}
	return nil
}

func (x *Envelope) GetScrapeProgress() *ScrapeProgress {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScrapeProgress); ok {
			return x.ScrapeProgress
		}
	}
	return nil
}

func (x *Envelope) GetLaunchRequest() *LaunchRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_LaunchRequest); ok {
			return x.LaunchRequest
		}
	}
	return nil
}

func (x *Envelope) GetKillRequest() *KillRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_KillRequest); ok {
			return x.KillRequest
		}
	}
	return nil
}

func (x *Envelope) GetProcessEvent() *ProcessEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProcessEvent); ok {
			return x.ProcessEvent
		}
	}
	return nil
}

func (x *Envelope) GetSearchRequest() *SearchRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SearchRequest); ok {
			return x.SearchRequest
		}
	}
	return nil
}

func (x *Envelope) GetSearchResponse() *SearchResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SearchResponse); ok {
			return x.SearchResponse
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_PreviewReady struct {
	PreviewReady *PreviewReady `protobuf:"bytes,1,opt,name=preview_ready,json=previewReady,proto3,oneof"`
}

type Envelope_ScrapeProgress struct {
	ScrapeProgress *ScrapeProgress `protobuf:"bytes,2,opt,name=scrape_progress,json=scrapeProgress,proto3,oneof"`
}

type Envelope_LaunchRequest struct {
	LaunchRequest *LaunchRequest `protobuf:"bytes,3,opt,name=launch_request,json=launchRequest,proto3,oneof"`
}

type Envelope_KillRequest struct {
	KillRequest *KillRequest `protobuf:"bytes,4,opt,name=kill_request,json=killRequest,proto3,oneof"`
}

type Envelope_ProcessEvent struct {
	ProcessEvent *ProcessEvent `protobuf:"bytes,5,opt,name=process_event,json=processEvent,proto3,oneof"`
}

type Envelope_SearchRequest struct {
	SearchRequest *SearchRequest `protobuf:"bytes,6,opt,name=search_request,json=searchRequest,proto3,oneof"`
}

type Envelope_SearchResponse struct {
	SearchResponse *SearchResponse `protobuf:"bytes,7,opt,name=search_response,json=searchResponse,proto3,oneof"`
}

func (*Envelope_PreviewReady) isEnvelope_Payload() {}

func (*Envelope_ScrapeProgress) isEnvelope_Payload() {}

func (*Envelope_LaunchRequest) isEnvelope_Payload() {}

func (*Envelope_KillRequest) isEnvelope_Payload() {}

func (*Envelope_ProcessEvent) isEnvelope_Payload() {}

func (*Envelope_SearchRequest) isEnvelope_Payload() {}

func (*Envelope_SearchResponse) isEnvelope_Payload() {}

var File_hypervane_proto protoreflect.FileDescriptor

const file_hypervane_proto_rawDesc = "" +
	"\n" +
	"\x0fhypervane.proto\x12\thypervane\"B\n" +
	"\fPreviewReady\x12\x15\n" +
	"\x06rom_id\x18\x01 \x01(\tR\x05romId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"q\n" +
	"\x0eScrapeProgress\x12\x15\n" +
	"\x06rom_id\x18\x01 \x01(\tR\x05romId\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x02R\apercent\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xe7\x01\n" +
	"\rLaunchRequest\x12\x15\n" +
	"\x06rom_id\x18\x01 \x01(\tR\x05romId\x12\x19\n" +
	"\brom_path\x18\x02 \x01(\tR\aromPath\x12\x1f\n" +
	"\vemulator_id\x18\x03 \x01(\tR\n" +
	"emulatorId\x12E\n" +
	"\toverrides\x18\x04 \x03(\v2'.hypervane.LaunchRequest.OverridesEntryR\toverrides\x1a<\n" +
	"\x0eOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\vKillRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"\xe3\x01\n" +
	"\fProcessEvent\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.hypervane.ProcessEvent.KindR\x04kind\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x15\n" +
	"\x06rom_id\x18\x03 \x01(\tR\x05romId\x12\x1d\n" +
	"\n" +
	"runtime_ms\x18\x04 \x01(\x04R\truntimeMs\x12\x1d\n" +
	"\n" +
	"crash_info\x18\x05 \x01(\tR\tcrashInfo\":\n" +
	"\x04Kind\x12\v\n" +
	"\aSTARTED\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\v\n" +
	"\aCRASHED\x10\x02\x12\v\n" +
	"\aMETRICS\x10\x03\"\xe4\x01\n" +
	"\bRomEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x04R\bfileSize\x12\x14\n" +
	"\x05crc32\x18\a \x01(\tR\x05crc32\x12\x12\n" +
	"\x04sha1\x18\b \x01(\tR\x04sha1\x12\x1a\n" +
	"\bverified\x18\t \x01(\bR\bverified\"o\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"^\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.hypervane.RomEntryR\aresults\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x02 \x01(\rR\ttotalHits\"\xe4\x03\n" +
	"\bEnvelope\x12>\n" +
	"\rpreview_ready\x18\x01 \x01(\v2\x17.hypervane.PreviewReadyH\x00R\fpreviewReady\x12D\n" +
	"\x0fscrape_progress\x18\x02 \x01(\v2\x19.hypervane.ScrapeProgressH\x00R\x0escrapeProgress\x12A\n" +
	"\x0elaunch_request\x18\x03 \x01(\v2\x18.hypervane.LaunchRequestH\x00R\rlaunchRequest\x12;\n" +
	"\fkill_request\x18\x04 \x01(\v2\x16.hypervane.KillRequestH\x00R\vkillRequest\x12>\n" +
	"\rprocess_event\x18\x05 \x01(\v2\x17.hypervane.ProcessEventH\x00R\fprocessEvent\x12A\n" +
	"\x0esearch_request\x18\x06 \x01(\v2\x18.hypervane.SearchRequestH\x00R\rsearchRequest\x12D\n" +
	"\x0fsearch_response\x18\a \x01(\v2\x19.hypervane.SearchResponseH\x00R\x0esearchResponseB\t\n" +
	"\apayloadB%Z#github.com/hypervane/connectors/ipcb\x06proto3"

var (
	file_hypervane_proto_rawDescOnce sync.Once
	file_hypervane_proto_rawDescData []byte
)

func file_hypervane_proto_rawDescGZIP() []byte {
	file_hypervane_proto_rawDescOnce.Do(func() {
		file_hypervane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypervane_proto_rawDesc), len(file_hypervane_proto_rawDesc)))
	})
	return file_hypervane_proto_rawDescData
}

var file_hypervane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hypervane_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hypervane_proto_goTypes = []any{
	(ProcessEvent_Kind)(0), // 0: hypervane.ProcessEvent.Kind
	(*PreviewReady)(nil),   // 1: hypervane.PreviewReady
	(*ScrapeProgress)(nil), // 2: hypervane.ScrapeProgress
	(*LaunchRequest)(nil),  // 3: hypervane.LaunchRequest
	(*KillRequest)(nil),    // 4: hypervane.KillRequest
	(*ProcessEvent)(nil),   // 5: hypervane.ProcessEvent
	(*RomEntry)(nil),       // 6: hypervane.RomEntry
	(*SearchRequest)(nil),  // 7: hypervane.SearchRequest
	(*SearchResponse)(nil), // 8: hypervane.SearchResponse
	(*Envelope)(nil),       // 9: hypervane.Envelope
	nil,                    // 10: hypervane.LaunchRequest.OverridesEntry
}
var file_hypervane_proto_depIdxs = []int32{
	10, // 0: hypervane.LaunchRequest.overrides:type_name -> hypervane.LaunchRequest.OverridesEntry
	0,  // 1: hypervane.ProcessEvent.kind:type_name -> hypervane.ProcessEvent.Kind
	6,  // 2: hypervane.SearchResponse.results:type_name -> hypervane.RomEntry
	1,  // 3: hypervane.Envelope.preview_ready:type_name -> hypervane.PreviewReady
	2,  // 4: hypervane.Envelope.scrape_progress:type_name -> hypervane.ScrapeProgress
	3,  // 5: hypervane.Envelope.launch_request:type_name -> hypervane.LaunchRequest
	4,  // 6: hypervane.Envelope.kill_request:type_name -> hypervane.KillRequest
	5,  // 7: hypervane.Envelope.process_event:type_name -> hypervane.ProcessEvent
	7,  // 8: hypervane.Envelope.search_request:type_name -> hypervane.SearchRequest
	8,  // 9: hypervane.Envelope.search_response:type_name -> hypervane.SearchResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hypervane_proto_init() }
func file_hypervane_proto_init() {
	if File_hypervane_proto != nil {
		return
	}
	file_hypervane_proto_msgTypes[8].OneofWrappers = []any{
		(*Envelope_PreviewReady)(nil),
		(*Envelope_ScrapeProgress)(nil),
		(*Envelope_LaunchRequest)(nil),
		(*Envelope_KillRequest)(nil),
		(*Envelope_ProcessEvent)(nil),
		(*Envelope_SearchRequest)(nil),
		(*Envelope_SearchResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypervane_proto_rawDesc), len(file_hypervane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypervane_proto_goTypes,
		DependencyIndexes: file_hypervane_proto_depIdxs,
		EnumInfos:         file_hypervane_proto_enumTypes,
		MessageInfos:      file_hypervane_proto_msgTypes,
	}.Build()
	File_hypervane_proto = out.File
	file_hypervane_proto_goTypes = nil
	file_hypervane_proto_depIdxs = nil
}
